CREATE DATABASE MONENERGY_DB;

USE MONENERGY_DB;

CREATE TABLE REGISTRY(
	Reg_ID SMALLINT AUTO_INCREMENT NOT NULL,
	Reg_Date DATE NOT NULL,
    Reg_Wing CHAR NOT NULL,
    Reg_Vaue FLOAT,

    CONSTRAINT PK_Reg_ID PRIMARY KEY (Reg_ID)
);

ALTER TABLE `registry` CHANGE `Reg_Date` `Reg_Date` DATETIME NOT NULL;